### ISSUE TITLE
Promotion Bug

### ISSUE THREAD

**Issue by goldipl** [Zasada94/pizza-portal#1] opened 2023-08-10 12:09 UTC
1. Open https://double-pizza.netlify.app/
2. Go to 'Promotions' & open https://double-pizza.netlify.app/promotions
3. Choose and click promotion for example 'Double Deal'
4. Scroll down to pizzas
5. Click for example four times on Double Pepperonis "Add button" 
6. Scroll up to the top of the page
7. Click "Cart (Order)" button
8.  Try to change quantity of Double Pepperoni pizzas
9. It doesn't work :(

**Comment by Zasada94** [comment] 2023-08-10 15:17
It is a feature not a bug - so noone can modify incart promo products. Fixed by adding promo info in these products.

**Closed as completed by Zasada94** 2023-08-10 15:17 UTC

**Comment by goldipl** [comment] 2023-08-11 13:42
Ok. Accepted 👍
